### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by KevinHansen23** [FACT-Finder-Web-Components/shopware6-plugin#265]
Hi,

we have installed the plugin and found a few bugs:

1.) When you click on one of the Pagination page-link Items nothing happens. The Console and the network Tab remain empty.
2.) When you configure the Price Filter as Range-Slider the dropdown does not close on outside click.
3.) The ProxyController is not called on initial page load.
4.) If you open the Filter offcanvas, close it, and open any other offcanvas, the Filter offcanvas stops working
5.) The `record.Price` Variable ist not formatted correctly. `.` instead of `,`.

Shopware Version: 6.6.8.2
Plugin Version: 2.2.0

Tested with Storefront- & Custom-Theme.

Kind regards
Kevin Hansen

**Comment by Rayn93** [comment]
@KevinHansen23  Thank you for finding these bugs.
Due to the end of cooperation with the Shopware Marketplace, we no longer update the plugin available there.
That is why we encourage you to use our official plugin available here instead: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/tree/release/6.x . 

After installation, could you confirm that the above problems still occur?

**Comment by KevinHansen23** [comment]
Hi @Rayn93 I have removed the old plugin from the store and installed the new one. I also updated the field roles and cleared the cache, but it got worse. Now it looks like this:

![grafik](https://github.com/user-attachments/assets/545ad61d-240f-4142-b41e-dce087733db7)

The `record.html.twig` startet using the `masterValues` Variable instead of the `record` Variable. But as I can see in the repsonse `masterValues` does not contain any data. Only `variantValues` contains data. When I switch the template variable to `{{ '{{variantValues.0.Name}}' }}` the data is shown.

Also, as soon as I activate our custom Theme which still uses the `record` Variable the data is shown also. 

The reported bugs 1, 2 & 4 still occur in Version 6.0.2. I haven't tested bug 3 yet. I also found a few additional ones:

6.) The Price Filter is completely empty:

![grafik](https://github.com/user-attachments/assets/c0f243bc-329e-4f2a-a2ca-e8bed7128e67)

After you use another filter the price filter looks like this:

![grafik](https://github.com/user-attachments/assets/d8aa6711-d966-4127-8b43-b850e2c7b857)

7.) The Category filter is now visible on category pages:

![grafik](https://github.com/user-attachments/assets/ce96f94c-1b15-4d37-9be8-a012367ba3d3)

Kind regards
Kevin Hansen

**Comment by Rayn93** [comment]
Hi @KevinHansen23 
We check it this week and try to fix it.
I will come back with information soon.

**Comment by KevinHansen23** [comment]
Hi @Rayn93 

thanks for the reply. In the meantime we were able to fix a few problems by reconfiguring some settings on the factfinder server. Here is a list of ongoing errors:

1. The Price Filter is still broken
2. The ProxyController is not called on initial page load.
3. If you open the Filter offcanvas, close it, and open any other offcanvas, the Filter offcanvas stops working
4. The record.Price Variable ist not formatted correctly. `.` instead of `,`. Also `5,90` is displayed as `5,9`.
5. The category filter is visible on category pages

The last error might be caused by the value of `categoryPathFieldName` in the `CategoryPageSubscriber`:

```php
        $event->getPage()->getExtension('factfinder')->assign(
            [
                'communication'           => $communication,
                'trackingSettings'        => $this->extensionConfig->getTrackingSettings(),
                'redirectMapping'         => (string) $this->extensionConfig->getRedirectMapping(),
                'searchImmediate'         => false,
                'categoryPathFieldName'   => "{$this->fieldName}ROOT", // Works without "ROOT"
                'communicationAttributes' => !empty($communicationConfig) ? $this->getCommunicationAttributes($communicationConfig) : $communication,
            ]
        );
```

**We also have the following challenge:** 
We are creating listing pages for Manufacturers. We were able to create the new listing page by creating custom `Page-` and `ResponseSubscribers` based on your `CategorySubscribers`. The listing itself is already filtered by Brand on initial page load.

Basically our last issue is the following:
On a category Page the main Filter is "Category" on the manufacturer page its "Brand". When you enter the page the "Clear all filters" Button is visible an you can reset the Brand filter by clicking the single reset button (In our Example "Breuer" is the Brand):

![grafik](https://github.com/user-attachments/assets/34802166-c978-4933-a246-1901b261f65d)

When you click on the reset all Button the uri becomes `?filter=CategoryPathRoot%3ABreuer` instead of `?filter=Brand%3ABreuer`. Also the Brand ASN Filter Group is still visible:

![grafik](https://github.com/user-attachments/assets/62b2f59b-00f9-4200-8539-ac37c7481bbf)

When we change the `categoryPathFieldName` in our `PageSubscriber` to `Brand` (feels a bit hacky) it fixes the uri and hides the Brand ASN Group Filter. But as soon as you click the reset all button we receive an error:

`Invalid value for Brand filter. TEXT values must be send as a string.` Which seems logical.

1. How can we prevent that the Brand reset button ("Breuer") button is visible on manufacturer pages?
2. What do we have to do to fix the uri when you click the reset all button?

Kind regards
Kevin Hansen

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

I've verified the issues you described on my development environment:

1. The price filter works fine for me:
<img width="1414" alt="Screenshot 2025-01-15 at 14 30 45" src="https://github.com/user-attachments/assets/de579dc6-49b2-4d24-a545-8d7913b05b00" />

Could you share a link to your site so I can see what's wrong?

2. ProxyController should be called every time a request is made to FactFinder API via webcomponents. If such a request is not made on your initial page then proxy controller will not be called either.

3. I confirm the issue with Filter off canvas for mobile view. We will try to fix it soon.

4. Price and currency can be easily configured using webcomponents formatting. Here you will find all information on how to do it:
https://web-components.fact-finder.de/documentation/5.x/formatting

5. It is a default behavior of webcomponents library. If you want to hide some filter you can do it via `hide-facets` attribute on` ff-asn`. Here you will find more information about it: https://web-components.fact-finder.de/api/5.x/ff-asn#tab=docs

**Brend pages**

Currently, we do not support brand pages in the SDK (we have such plans for Q1/Q2 2025). But it can be done in a very similar way as with category pages. Most likely something is wrong in your configuration, so please check the **Brand pages** section on this documentation page: https://web-components.fact-finder.de/documentation/5.x/category-pages

**Comment by KevinHansen23** [comment]
Hi @Rayn93 

thanks for the fast reply.

**1. Price Filter** 

The Price filter bug seems only to appear, when you configure the filter as Slider:

![grafik](https://github.com/user-attachments/assets/8790f91d-793a-4f08-af60-cd41d71ae525)

**2. ProxyController**

Could you elaborate on that? 

What I mean is that a customer enters the store at `www.store.com/category`. The FactFinder listing and ASN is displayed, but the ProxyController is never called. Now the customer uses the ASN, and the ProxyController is called.

If the purpose of the ProxyController is to enrich the data, there would be two different listings. Listing `#1` when you enter a category page and listing `#2` when the customer uses the ASN.

And lastly thanks for the links. That looks promising.

**Update:** 

We just found another bug on the Product Detail Page:

![grafik](https://github.com/user-attachments/assets/4ff1c534-39bc-4934-a83d-caa06d2df580)

Here is an example Response: 

```
Client error: `GET https://[redacted].fact-finder.de/rest/v5/campaign/shopware6/product?id=527094&idType=productNumber&sid=[redacted]` resulted in a `404 Not Found` response:<html><head><title>404 Not Found</title></head><body><center><h1>404 Not Found</h1></center><hr><center>nginx/1. (truncated...)
```

Also the following script in the `base.html.twig` uses the old `ffReady` Event:

```
  {% block base_script_factfinder_search_redirect %}
    <script>
      document.addEventListener('ffReady', function (e) {
        e.eventAggregator.addBeforeHistoryPushCallback(function (res, event, url) {
          url = url.replace(/filter=CategoryPath[^&]+&?/, '').replace(/order=[^&]+&?/, '').replace(/name=[^&]+&?/g, '');
          factfinder.communication.Util.pushParameterToHistory(res, url, event);
          return false;
        });
      });
    </script>
  {% endblock %}
```

Kind regards
Kevin Hansen

**Comment by omikron-fp** [comment]
Hi @KevinHansen23, regarding the **price filter** issue.
Do you have a custom template defined for the `ff-asn-group-slider` element or are you using the default one.
The default template has a known issue that looks very much like in your screenshot.

Try to define a custom template. The issue should disappear.
See **Sliders** in https://web-components.fact-finder.de/api/5.x/ff-asn.

**Comment by KevinHansen23** [comment]
Hi @omikron-fp, we were using the default implementation.
But even if I change the template based on the documentation it looks like this:

![Image](https://github.com/user-attachments/assets/b4c3752a-62af-452e-abde-bdfd4bc0163d)

```html
<ff-asn-group-slider class="filter-panel-item dropdown">
    <div slot="groupCaption" class="filter-panel-item-toggle btn">
        <span>{{ '{{group.name}}' }}</span>
        <span class="float-end">
            {% sw_icon 'arrow-head-down' style { 'size': 'xs', 'class': 'filter-panel-item-toggle' } %}
        </span>
    </div>

    <div data-container="removeFilter">
        <span>Reset Filter</span>
    </div>

    <ff-slider-control submit-on-input="true">
        <div>
            <input data-control="min">
            <input data-control="max">
        </div>
        <ff-slider></ff-slider>
    </ff-slider-control>
</ff-asn-group-slider>
</ff-asn>
```

We might be able to fix this with a lot of custom CSS but there is even a `false` in the source code:

![Image](https://github.com/user-attachments/assets/ad1d520b-d281-4d29-b578-ef1a4d7fcbd4)

Kind regards
Kevin Hansen

**Comment by omikron-fp** [comment]
Hi @KevinHansen23, sorry for the trouble. The slider is indeed much more broken than I had anticipated.
We are already working to release a fix by the end of the week.

If this topic is very urgent to you, you can mitigate the bug somewhat by doing the following:

Switch to One-Touch slider `<ff-slider one-touch></ff-slider>`.

Hide triangle with CSS `.ffw-triangle { display: none; }`.

_Optional_: Give `ff-slider-control` a bit more bottom padding. `ff-slider-control { padding-bottom: 50px; }`.
This would be because the `.ffw-slider-container` acts as the 'canvas' to the one-touch triangle and might overlap with surrounding elements.

**OR**: Give the One-Touch Slider a go. Then it should be enough to add the `one-touch` attribute to `ff-slider`.

**Comment by KevinHansen23** [comment]
Hi @omikron-fp, we can definitely wait until the end of the week.

Do you have an ETA for the other bugs?

Edit: I might have found another problem. In the Documentation for Version 5.x you state that the underlying Template Engine is handlebars.js instead of mustache.js. But as soon as we write the following we receive a mustache.js Exception:

```twig
{{ '{{#if masterValues.Name }}' }}
    Test: {{ '{{ masterValues.Name }}' }}
{{ '{{/if }}' }}
```

```
[Mustache_Exception_SyntaxException](https://localhost/[category]/)
HTTP 500 Internal Server Error
Nesting error: if masterValues.Name (on line 44) vs. if (on line 46)
```

When we switch back to mustache.js Syntax the condition is not working:

```twig
{{ '{{#masterValues.Name }}' }}
    Test: {{ '{{ masterValues.Name }}' }} 
{{ '{{/masterValues.Name }}' }}
// Output: "Test: "
```

Kind regards
Kevin Hansen

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

We already fixed problem with Filters on mobile view: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/c46cec06fba62f3284020b88d9a7b4499f1ef586

Now we are working with proxy issue on product details page. Probably tomorrow we will merge fix for it. 

A new release containing fixes is planned for the end of this week.

**Comment by Rayn93** [comment]
@KevinHansen23 

I checked the template engine problem and it only occurs for SSR (server side rendering). This week we will try to replace Mustache with Handlebars in SSR so that only one system can be used everywhere.

For now, you can disable the SSR option so that you can use Handlebars in templates without any problems.

**Comment by KevinHansen23** [comment]
Hi @Rayn93 thanks for the regular updates.

I'm afraid we have found another bug. When I remember it correctly, in the SDK the CategoryPath is comma separated, like `Bath, Bathroom ceramics, Washbasins`.

The problem now occurs when you have a Category name that includes a comma like `name, name & name`. This will result in a wrong CategoryPath like `Bath, Bathroom ceramics, Washbasins, name, name & name`.

Kind regards
Kevin Hansen

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Thanks for noticing and reporting Category page bug. It's already been fixed here: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/4df7e5a321bccdf679664f1f8e5b1dbc5a017346

We have also already fixed the proxy issue on product detail page that you described a few days ago: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/60296798f742c90a9873090ca2745162985bca60

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

We have just released a new version (v6.1.0) of the SDK which includes fixes from this issue:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/releases/tag/v6.1.0

Please check the new version of the plugin. The above issues should be resolved now.

**Comment by KevinHansen23** [comment]
HI @Rayn93 I've installed and tested the new Version.

**I can confirm the following is fixed:**

- The offCanvas Filter now works even after you opened another offCanvas Menu
- Categories with a comma in their name do not break the filter anymore
- if conditions with handlebars.js output the expected result
- The Price Filter works better (but still does not close on outside click)

**The following is still broken:**

- The ProxyController is not called on initial Page Load
- The Product Page still throws an error (`GET https://[redacted].fact-finder.de/fact-finder/rest/v5/records/shopware6/recommendation?id=778427&maxResults=4&sid=[redacted] resulted in a 403 Forbidden response:{"error":"Forbidden","errorDescription":"Neither the 'recommendation engine' module nor the 'loop recommendation' module truncated`)
- The `CategoryPath` is still written to the URL when you use the ASN (and in our case also the brand name on a brand page)

**Regarding the product page:** Since Shopware Version 6.6 the product page is based completely on CMS Elements. Maybe it would be a good way to also implement FactFinder into the product page with cms elements like it is already done on the category pages.

Kind regards
Kevin Hansen

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Regarding the remaining problems:

1. Could you describe better what you mean by initial page load? Unfortunately, I cannot open such a situation in my environment that a request to fact-finder does not go through the proxy when this function is enabled. Even when I enter the category page for the first time in incognito mode, the request is passed through the proxy.

2. It seems that your fact-finder plan does not have the recommendation (it is a additional paid option) function enabled. Unfortunately, at the moment it is not possible to disable the use of recommendation from the plugin level, but I will try to add such a function to the SDK in the near future.

3. In the next version of the plugin, we will introduce such a change that this filter will not appear on category pages.

As for CMS Elements for the search result page, we will think about it. Unfortunately, it would most likely be a breaking change, so it could appear from version 7.x of the plugin at the earliest.

**Comment by KevinHansen23** [comment]
Hi @Rayn93,

**regarding the ProxyController:** Currently our configuration has enabled the Proxy Controller:

![Image](https://github.com/user-attachments/assets/2de92fb3-ba45-40c1-8e92-5999b100eff6)

Then we have created the following Subscriber:

```php
<?php

declare(strict_types=1);

namespace ...;

use Omikron\FactFinder\Shopware6\Events\EnrichProxyDataEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class EnrichFactFinderDataSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [EnrichProxyDataEvent::class => 'enrichData'];
    }

    public function enrichData(EnrichProxyDataEvent $event)
    {
        $data = $event->getData();
        
        // do Stuff

        $event->setData($data);
    }
}
```

When I enter any Category the subscriber is not called. It does not matter if the url has filter query parameters or not. When I use the ASN on the same Category the subscriber is called. The Subscriber is also called when I enter a product page.

I also tried a breakpoint inside the `Omikron\FactFinder\Shopware6\Storefront\Controller\ProxyController.php`:

![Image](https://github.com/user-attachments/assets/bc453acd-b6d0-4b69-8c67-25d639c87a66)

The breakpoint is never reached when I initially enter the Category Page.

**Regarding the recommendation engine:** Do you know when this will happen? We don't want to go live with a shop that throws errors. Btw: The Cart seems to have the same problem.

Regarding the URL: Pretty much see same question: Do you know when? This has a follow up bug where the reset all button shows up even though there is nothing to reset when you enter a page with the CategoryPath URL Parameter.

Kind regards
Kevin Hansen

**Comment by Rayn93** [comment]
@KevinHansen23 

Thank you for explain me  your problem with proxy. I will try to reproduce it one more time.

The fix for category path filter in URL on category page is ready: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/26133f26e0e04354c1e3691346adbde5d0bec746

This week I will try to implement the configuration to disable recommendation in SDK.

**Comment by KevinHansen23** [comment]
@Rayn93 nice, that was fast. And thanks for the reply on the other two issues.

**Comment by KevinHansen23** [comment]
There is another console error that occurs when the "Display buy buttons in listings" feature is enabled (`Settings -> Shop -> Product`):

![Image](https://github.com/user-attachments/assets/26fce7a5-9a50-48ea-820e-a3f302fe3918)

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Unfortunately I can't reproduce this error with the add to cart button. The display buy buttons in listings is probably enabled by default (at least that's how it was for me) and I've never seen such a problem. Where does it show up for you? Can you send me a link to your staging website so I can verify it?

I also checked the proxy again according to your example and the proxy is enabled every time a request is made to the FactFinder API:

![Image](https://github.com/user-attachments/assets/630f2cf1-7672-48a1-a255-1a3462e176c1)


Maybe you have some custom code / other plugin that causes this problem?

BTW. Today I merged a new function that allows you to disable additionally paid functionalities: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/dfa2e244b4f7e3d9a2e31127814be980b3c74425

**Comment by KevinHansen23** [comment]
Hi @Rayn93 the commit looks really good, thanks.

**Regarding the ProxyController:** I switched the template to default and deactivated every plugin, the breakpoint is still not reached. 

But your Screenshot gave me an Idea. The ProxyController Bug only occurs with activated SSR. As soon as I deactivate it, the breakpoint is reached. Can you reproduce the behaviour this way?

**Regarding the console error:** Where can I send you the credentials and the link to our dev environment?

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Thanks for the advice on the proxy error with SSR. Today we added Proxy support for SSR: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/aad5dc385b975f35788e1395f6a9c9a8d2fb9cb9

**Regarding the console error**: have you checked if this error also occurs when you use the default shopware template like you did for the proxy? The credentials for your dev env you could send here: ext-robert.saternus@fact-finder.com

**Comment by KevinHansen23** [comment]
Hi @Rayn93,

**regarding the ProxyController:** That's perfect, thank you very much.

**Regarding the console error:** Yes, I've tested the behaviour with the default template enabled. You should have received an email with the necessary credentials.

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Thank you for access to your website. Unfortunately I didn't find any issue with SDK on start page in section: Breuer Panorama Duschkabinen:

<img width="1430" alt="Image" src="https://github.com/user-attachments/assets/f6029273-e177-483c-b77e-1436bf6ac5be" />

Could you describe me how could I find this error?

**Comment by KevinHansen23** [comment]
Hi @Rayn93, have you added an Item to the cart?

**Comment by Rayn93** [comment]
Now I can see it. Thanks.
The error is connect with our tracking system. I will prepare a fix for it.

**Comment by KevinHansen23** [comment]
Hi @Rayn93, today we tried to export the CMS pages. But the export was, except for the header, empty.
To test the export we created a new Landingpage under Catalogues -> Categories -> Landingpage. 

When we manually include a Category via the custom field the Category is exported into the cms feed:

![Image](https://github.com/user-attachments/assets/11e1ffa1-b4ad-4c91-80ea-ee4231ff2cb2)

But this flag only exists for Categories and not for Landingpages. Do we miss out on something, or how are we supposed to export the CMS pages?

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Here is a fix for add to cart issue: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/534fc6e60e50d50da1975352d30bc735c99ef1bd

Regarding the CMS export: currently the SDK cms export supports only category pages. We plan to do this for landing pages as well, but due to other priorities it will most likely not be ready in Q1 2025.

**Comment by KevinHansen23** [comment]
Hi @Rayn93 thanks for the clarification on the CMS Export. We can wait, It's more like a nice to have feature and not mandatory.

If I see it correctly, everything except for the PriceFilter Issue is fixed. Is that problem with the webComponents itself or the Plugin?

Do you have an ETA for when you will release the new Version?

**Comment by Rayn93** [comment]
@KevinHansen23 probably tomorrow I will released a new plugin version. I will inform you here when the release is ready

Regarding price filter - do you mean this issue:

`The Price Filter works better (but still does not close on outside click) ` ?

As far as I know, this is the default behavior of price filter. @omikron-fp  Could you please confirm this?

**Comment by KevinHansen23** [comment]
Hi @Rayn93, yes that's what I mean. If the filter would stay open while you are using it, it would be fine. But it simply never closes. Even if you interact with a totally different filter, the pagination etc. the Price filter stays open. The only way to close it, is to click on the `filter-panel-item-toggle`. 

Every other filter behaves like you would expect and closes if you click anywhere else on the page.

**Comment by omikron-fp** [comment]
Filter groups don't have a built-in dropdown behaviour. There must be an external trigger that manually closes them.
Is that trigger perhaps hooked on some specific HTML structure in the slider group that is different when configured as range?

**Comment by KevinHansen23** [comment]
Hi @omikron-fp thanks, I found the problem.

@Rayn93 the `asn-plugin.js` only handles "normal" filters. I extended the `_handleToggleFilter()` method to make it work with slider Filters also:

```javascript
    _handleToggleFilter(event) {
        const getAllGroupsExceptClicked = e => {
            const clickedGroup = e.target.closest('ff-asn-group, ff-asn-group-slider');
            return [...document.querySelectorAll('ff-asn-group, ff-asn-group-slider')].filter(g => g !== clickedGroup)
        }

        const isAsnGroup = e => {
            return this._eventPath(e).find(p => p.tagName === 'ff-asn-group'.toUpperCase())
                || this._eventPath(e).find(p => p.tagName === 'ff-asn-group-slider'.toUpperCase());
        }

        if (!isAsnGroup(event)) {
            document.querySelectorAll('ff-asn-group, ff-asn-group-slider').forEach(g => {
                if (g.opened) g.toggle(true);
            })
        }

        if (isAsnGroup(event)) {
            getAllGroupsExceptClicked(event).forEach(g => {
                if (g.opened) g.toggle(true);
            })
        }
    }

```

Could you integrate this fix?

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Fix for price filter is ready: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/9840b5e0cd38c05549aa1e95354ef93b9d608c1a

Thank you for the sample repair code.

Have all your issues been fixed?

**Comment by KevinHansen23** [comment]
Hi @Rayn93 yes, that should have been all

**Comment by Rayn93** [comment]
@KevinHansen23 
Due to yet another new feature being developed the release of the new SDK version will be delayed a bit. I think it will most likely be on Monday/Tuesday.

**Comment by KevinHansen23** [comment]
Hi @Rayn93 we will wait eagerly :-)
Have a nice weekend.

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Thanks for your patience. Release is ready: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/releases/tag/v6.2.0

**Comment by KevinHansen23** [comment]
Hi @Rayn93 I've installed the new Version and as far as I can tell right now the bugs seem to be fixed.

But now as soon as the Proxy is enabled the Plugin throws a HTTP 500 Status Code because it is not compatible with Basic Authentication:

```
2025-02-11T12:26:30.455255+00:00] request.CRITICAL: Uncaught PHP Exception Omikron\FactFinder\Communication\Client\ClientException: "Client error: `GET https://[redacted]/fact-finder/proxy/rest/v5/navigation/shopware6_dev` resulted in a `401 Unauthorized` response: <!DOCTYPE html> <html style="height:100%"> <head> <meta name="viewport" content="width=device-width, initial-scale=1, sh (truncated...) " at HttpErrors.php line 29 {"exception":"[object] (Omikron\\FactFinder\\Communication\\Client\\ClientException(code: 401): Client error: `GET https://[redacted]/fact-finder/proxy/rest/v5/navigation/shopware6_dev` resulted in a `401 Unauthorized` response:\n<!DOCTYPE html>\n<html style=\"height:100%\">\n<head>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, sh (truncated...)\n 
at .../vendor/omikron/factfinder-communication-sdk/src/Client/Middleware/HttpErrors.php:29)\n[previous exception] [object] (GuzzleHttp\\Exception\\ClientException(code: 401): Client error: `GET https://[redacted]/fact-finder/proxy/rest/v5/navigation/shopware6_dev` resulted in a `401 Unauthorized` response:\n<!DOCTYPE html>\n<html style=\"height:100%\">\n<head>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, sh (truncated...)\n at /home/banemo/public_html/shopware6/dev/releases/129/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111)"} []
```

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Unfortunately, I can't reproduce this 401 error on my local environment. Could you describe better when you get the error and what exactly it is related to? The 401 error would suggest that you don't have access to some resource in FactFinder.

Edit. I think I reproduced the error you wrote about. It appears for me when I use SSR / Proxy and my API key is invalid. Is that what you meant?

**Comment by KevinHansen23** [comment]
Hi @Rayn93, SSR and Proxy is enabled but our API key is valid. As soon as I comment out the Basic Authentication in the `.htaccess` everything works again. The error only occurs since v6.2.0. So I think PR #275 has something to do with this.

Also we found a weird behaviour regarding the facets and the EnrichDataEventSubscriber. What we want is to rename a facet element name. When we rename the unselected facet it works as expected:

```php
if ($facet['associatedFieldName'] === 'StockStatus' and isset($facet['elements'][0])) {
   $facet['elements'][0]['text'] = "Nur Lagerware anzeigen";
}
```

When it is selected the facet has no more elements. So we figured we have to rename the filter element:

```php
if ($filter['name'] === 'StockStatus' and isset($filter['values'][0])) {
    $filter['values'][0]['value'] = "Nur Lagerware anzeigen";
}
```

In xdebug I can see that the renaming works but the template is still rendered with the old name.

**Comment by Rayn93** [comment]
Hi @KevinHansen23 

Please check swagger documentation. For selected facets you should use `selectedElements` attribute:

![Image](https://github.com/user-attachments/assets/92b21208-13e7-4b8a-b287-d6b3e220059a)

I hope it will help fix your issue with facets.

**Comment by KevinHansen23** [comment]
Hi @Rayn93, thanks. No idea why I haven't seen this.

We found another bug in the tracking Plugin. Our Product Detail Page has multiple Add to Cart buttons due to crossselling. When you add the main Product to the cart the tracking calls are multiplied by the number of cart forms on the page. Sometimes the Product isn't even added to the cart. The Screenshot below is the result of one click:

![Image](https://github.com/user-attachments/assets/fe3ea193-bb3f-44c8-be84-a699947abf93)

This behaviour does not apply to the crossselling Products on the detail Page, only to the Main Product.

**Comment by KevinHansen23** [comment]
Hi @Rayn93, small update regarding the Basic Authentication Error: I could recreate the problem locally. As soon as the Proxy is enabled the plugin makes a Guzzle request to itself:

![Image](https://github.com/user-attachments/assets/ec4326fb-8a62-4270-8909-630aef35a976)

If this behaviour is correct, the solution would be to extend the `.htaccess`:

```
...
SetEnvIf Request_URI /api noauth=1
SetEnvIf Request_URI /fact-finder/proxy/rest noauth=1

<RequireAny>
    Require env noauth
    Require env REDIRECT_noauth
    Require valid-user
</RequireAny>
```

**Comment by Rayn93** [comment]
Hi @KevinHansen23 
Thank you for your update. I'll check it out on my end and if everything is OK I'll add this code to the documentation. Thanks.

BTW. Yesterday I uploaded a patch that fixes a bug in the tracking plugin: https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/e3aae3f55e6ae88117b8b159945d4b0bffaecc5c

**Comment by KevinHansen23** [comment]
Hi @Rayn93 I recreated the tracking Plugin fix locally and the bug is gone.

**Comment by KevinHansen23** [comment]
Hi @Rayn93, could tell us if the following is possible:

Per default Shopware 6 displays all Products of a Category no matter if the Category has Sub-Categories or not. Imagine the following structure:

```
Category 1
| Category 1.1
  | Category 1.1.1
  | Category 1.1.2
| Category 1.2
Category 2
```
In the current Version of the SDK the Category Filter is not visible on any Level. The expected behaviour would be the following:

- **Category 1:** Category-Filter is visible. The Current Category is not visible or can't be deselected (`implicit` or `fixed`)
- **Category 1.1 & 1.2:** Category-Filter is visible. The Current Category and Parent Categories are not visible or can't be deselected (`implicit` or `fixed`)
- **Category 1.1.1 & 1.1.2:** Filter is not visible (Current behaviour)

Hiding the Category Filter on the last level would be easily implementable using the `hide-facets` funtion. The main problem seems to be to show the Filter at all.

**Comment by omikron-fp** [comment]
Hi @KevinHansen23, let me recap to make sure I correctly understand your requirement.

Whenever you are on a category page that has further sub-categories, you want the category facet (basically the `ff-asn-group`) visible. Probably to allow users to filter deeper into sub-categories.
And when you navigate to a "leaf" category page that has no further sub-categories, you want to hide the category, as it is currently default for all category levels.
Is this about right?

You can indeed manipulate the `hide-facets` attribute on `ff-asn`. Although you probably don't need to do this client side. When navigating to a different category page, you probably do a full server round trip, and therefore all of this logic can sit on the server.
Are you using SSR? If so, you could analyse your server-side FactFinder response to detect whether there are sub-categories or not, and set the `hide-facets` attribute accordingly.
Would this be a workable approach for you?

If, however, you must take a client-side approach, similar logic should be possible by listening to `ResultDispatcher.addCallback("asn", fn)`. But I recommend to give the server-side approach a try first.

**Comment by KevinHansen23** [comment]
Hi @omikron-fp, thanks that put us in the right direction. We could accomplish the desired behaviour.

**Comment by KevinHansen23** [comment]
Hi @Rayn93, do you have an ETA for when you will Release the Tracking Fix #281?

**Comment by Rayn93** [comment]
Hi @KevinHansen23 
I am going to do it tomorrow.

**Comment by Rayn93** [comment]
@KevinHansen23 release is ready: 
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/releases/tag/v6.3.0

**Comment by KevinHansen23** [comment]
Hi @Rayn93, thanks looks good.

**Comment by KevinHansen23** [comment]
Hi @Rayn93 we found 2 smaller bugs:

1) On the mobile Viewports the Position of the right handle of the price filter is not always calculated correctly:

![Image](https://github.com/user-attachments/assets/abea9b5d-9c2c-4e42-a748-1a77556f8831)

Sometimes the position is `left: 0` (overlapping with the left handle) and sometime it is somewhere in the middle of the slider.

2) The `Reset all` Filter is not displayed in the Filter offCanvas if you close an reopen the offCanvas.

Before closing:

![Image](https://github.com/user-attachments/assets/d46cabe8-60fa-4620-a720-cc5b41264d94)

After closing and reopening:

![Image](https://github.com/user-attachments/assets/079f4587-dbdf-467d-ba4b-0c41c7bb467e)

**Comment by Rayn93** [comment]
Hi @KevinHansen23 
Thanks for reporting these issues. I will check it.

**Comment by Rayn93** [comment]
Hi @KevinHansen23 
Fix for `Reset all` button on mobile view is ready: 
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/373831be1bd5028a306461c433b661565549d768

Unfortunately I am unable to reproduce this error with price filter. Could you send me a link to your page where this error occurs?

**Comment by KevinHansen23** [comment]
Hi @Rayn93 do you still have the login data to our dev Environment?

If so, open any category page switch to mobile view and open the filter offCanvas. As soon as you click on the Price Filter the bug appears.

**Comment by KevinHansen23** [comment]
Hi @Rayn93 we have just realised that the product export uses more memory than our memory limit of 8GB and causes an error. There seems to be a memory leak here.

**Comment by Rayn93** [comment]
Hi @KevinHansen23 
Do you implement any custom fields for your export process?

**Comment by KevinHansen23** [comment]
Hi @Rayn93 we extend the Product Export with 15 Columns like this:

```php
<?php

declare(strict_types=1);

namespace Web\BanemoTheme\FactFinder\Export\Field;

use Omikron\FactFinder\Shopware6\Export\Data\Entity\ProductEntity;
use Omikron\FactFinder\Shopware6\Export\Field\FieldInterface;
use Shopware\Core\Framework\DataAbstractionLayer\Entity;

class ManufacturerNumber implements FieldInterface
{
    public function getName(): string
    {
        return 'ManufacturerNumber';
    }

    public function getValue(Entity $entity): string
    {
        return (string)$entity->getManufacturerNumber();
    }

    public function getCompatibleEntityTypes(): array
    {
        return [ProductEntity::class];
    }
}
```

The Product CustomFields are all blacklisted, so the customFields Column in the export file is empty.

**Comment by Rayn93** [comment]
@KevinHansen23
Please try to export without any extra fields. If the memory problem does not appear, it means that some of your extra fields are problematic and are causing a heavy load on the database.

**Comment by KevinHansen23** [comment]
Hi @Rayn93 we decided to integrate the export/upload/import functionality into our ERP, because we can't remove any of the fields. So, at least for us, you don't need to look closer into this Issue.

**Comment by Rayn93** [comment]
Hi @KevinHansen23 
Thank you for update.

In the meantime we have fixed the problem with price filter for mobile view that you found.
The release of the new version of SDK is ready:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/releases/tag/v6.3.2

**Comment by KevinHansen23** [comment]
Hi @Rayn93 we installed the update and everything looks good. 👍

**Comment by Rayn93** [comment]
I'm closing this ticket since all issues have been resolved.
